### ISSUE TITLE
tagger.get_entities() only returns 'TITLE': ['Not Found - CUPS v1.7rc1']

### ISSUE THREAD

**Issue by ghost** [dat/pyner#6]
On setting the connection with 
tagger = ner.HttpNER(host='127.0.0.1', port=631)
and using any sentence in tagger.get_entites("..."),
this is the result returned:
{'TITLE': ['Not Found - CUPS v1.7rc1']}

**Comment by dat** [comment]
Did you run and deploy the Stanford NER as a .war file to an Apache server first? You need that server running before you can connect to it.

https://github.com/dat/stanford-ner

**Comment by dat** [comment]
I'll consider this issue closed.
