### ISSUE TITLE
"No module named Ner"

### ISSUE THREAD

**Issue by akritaag** [dat/pyner#9]
Hogwarts:pyner-master Akrita$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing ner.egg-info/PKG-INFO
writing top-level names to ner.egg-info/top_level.txt
writing dependency_links to ner.egg-info/dependency_links.txt
reading manifest file 'ner.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ner.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-intel/egg
running install_lib
running build_py
creating build/bdist.macosx-10.9-intel/egg
copying build/lib/.DS_Store -> build/bdist.macosx-10.9-intel/egg
creating build/bdist.macosx-10.9-intel/egg/ner
copying build/lib/ner/.DS_Store -> build/bdist.macosx-10.9-intel/egg/ner
copying build/lib/ner/**init**.py -> build/bdist.macosx-10.9-intel/egg/ner
copying build/lib/ner/client.py -> build/bdist.macosx-10.9-intel/egg/ner
copying build/lib/ner/exceptions.py -> build/bdist.macosx-10.9-intel/egg/ner
copying build/lib/ner/utils.py -> build/bdist.macosx-10.9-intel/egg/ner
byte-compiling build/bdist.macosx-10.9-intel/egg/ner/**init**.py to **init**.pyc
byte-compiling build/bdist.macosx-10.9-intel/egg/ner/client.py to client.pyc
byte-compiling build/bdist.macosx-10.9-intel/egg/ner/exceptions.py to exceptions.pyc
byte-compiling build/bdist.macosx-10.9-intel/egg/ner/utils.py to utils.pyc
creating build/bdist.macosx-10.9-intel/egg/EGG-INFO
copying ner.egg-info/PKG-INFO -> build/bdist.macosx-10.9-intel/egg/EGG-INFO
copying ner.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-intel/egg/EGG-INFO
copying ner.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-intel/egg/EGG-INFO
copying ner.egg-info/top_level.txt -> build/bdist.macosx-10.9-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ner-0.1-py2.7.egg' and adding 'build/bdist.macosx-10.9-intel/egg' to it
removing 'build/bdist.macosx-10.9-intel/egg' (and everything under it)
Processing ner-0.1-py2.7.egg
Copying ner-0.1-py2.7.egg to /Library/Python/2.7/site-packages
Adding ner 0.1 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/ner-0.1-py2.7.egg
Processing dependencies for ner==0.1
Finished processing dependencies for ner==0.1
Hogwarts:pyner-master Akrita$ 

Then when I "import ner" it says no such package.

I am a beginner at python. Can you tell me where might I be going wrong?

**Comment by dat** [comment]
http://www.pip-installer.org/en/latest/

https://pypi.python.org/pypi/ner/0.1

http://simononsoftware.com/virtualenv-tutorial/

Use pip as your package manager and just install from Python Package Index. Use virtualenv if necessary.

**Comment by akritaag** [comment]
Thanks dat , that worked :+1:
